### ISSUE TITLE
Is LAMA p-tuning seeking a global prompt representation across relation?

### ISSUE THREAD

**Issue by asahi417** [THUDM/P-tuning#10]
Hi, I read the paper and found it very interesting! When you apply p-tuning on LAMA dataset, is the encoder for pseudo token shared across different relation types or do you train separate embedding for each relation type? After looking over the code, I believe the encoder trained via p-tuning is a global and not conditioned by relation types, but just want to double check.

Presumably the encoder is globally shared across relation types, does p-tuning really need that large training dataset like AutoPrompt? AutoPrompt optimized the prompt per relation (can be confirmed with [their official release of generated prompts](https://github.com/ucinlp/autoprompt/blob/master/prompts/fact_retrieval_bert_prompts.jsonl))
 and that's one of the reason why they need the large training data for each relation type (1000 data points per relation). 

Meanwhile, p-tuning seems to be more efficient because of the continuous optimization and shared encoder, so I feel it could establish very strong baseline even with a few shot setting. Have you done any ablation studies to see whether it works with a limited data points? I'm very curious about the result if you have it.

Thank you for sharing the code and your work!

**Comment by Xiao9905** [comment]
Hi asahi417,

The LAMA p-tuning is still a relation-dependent one. We train a set of continuous prompts for each relation respectively.  In LAMA/cli.py line 35,
`    parser.add_argument("--relation_id", type=str, default="P1001")`
we assign the relation_id to train. No matter discrete prompts or continuous prompts, I think they all play a similar role of relation embedding in traditional translational knowledge graph embedding, so it is not very probable that we can train a global prompt for all relation types.

About your second question, on Few-shot SuperGLUE, we present P-tuning's SOTA performance on few-shot NLU benchmarks. On LAMA, we have not conducted such experiments. I think it would be interesting to see P-tuning's results on fewer data points, and we will add it to our next update.

**Comment by asahi417** [comment]
Thank you for the quick reply and appreciate for the correction!
