### ISSUE TITLE
Potential bug in learning rate schedule for few-shot

### ISSUE THREAD

**Issue by lxuechen** [THUDM/P-tuning#13]
Hi, 

I recently refactored some of the code for my own research, and I may have spotted a potential bug in the learning rate schedule. 

To pinpoint, I'm referring to this [line](https://github.com/THUDM/P-tuning/blob/df0c1802f4e99ef32b0da13eaea594e63e120c4e/PT-Fewshot/pet/wrapper.py#L316). It seems `embedding_scheduler` should be created with `embedding_optimizer` as input, as opposed to `optimizer`.

**Comment by Xiao9905** [comment]
Solved in recent update. Thank you very much.
