### ISSUE TITLE
A problem about the prompt

### ISSUE THREAD

**Issue by logoutlzh** [THUDM/P-tuning#2]
Is the input of bi-directional model randomly initialized in the process of p-tuning?  Or It's the embedding of template. The pseudo prompts in Figure 2(b) seems to indicate that the model needs to use template embedding as input. I'm a little confused about this description.

**Comment by Xiao9905** [comment]
The pseudo prompts are randomly initialized, which serve as the placeholders. And to think from another perspective, this is because we can only randomly initialize the prompt encoder.

**Comment by Xiao9905** [comment]
Thanks for your comment, and we will better clarify it.

**Comment by logoutlzh** [comment]
I get it. This makes sense. Thank you for the reply.
