### ISSUE TITLE
能否测试一下小样本学习基准-中文版(FewCLUE)的效果?

### ISSUE THREAD

**Issue by brightmart** [THUDM/P-tuning#23]
感谢开源相关工作。目前的实验都是在英文上的，能否测试一下小样本学习基准，中文版(FewCLUE)上的效果?https://github.com/CLUEbenchmark/FewCLUE

**Comment by Xiao9905** [comment]
谢谢您的建议。不过目前我们暂时没有这方面的计划，欢迎您能实现一个版本，我们很乐意在README中提及您的仓库。

**Comment by brightmart** [comment]
感谢回复。已经实现了一个支持FewCLUE任务的ptuning. https://github.com/cluebenchmark/fewclue
