### ISSUE TITLE
P-tuning如何用于Question answering

### ISSUE THREAD

**Issue by yuhangjiang22** [THUDM/P-tuning#34]
您好，我是nlp初学者，有一个问题想请教大神。请问如何用代码实现将P-tuning用于Question answering？具体就是把QA task 的input里的question替换为p-tuning，代码方面烦请大神指点指点。不胜感激。

**Comment by Xiao9905** [comment]
@yuhangjiang22 Hi,

你可以参考一下我们在[P-Tuning v2](https://github.com/THUDM/P-tuning-v2)中对extractive QA的实现。
