### ISSUE TITLE
关于p-tuning中训练loss变为nan

### ISSUE THREAD

**Issue by effort-yq** [THUDM/P-tuning#35]
利用开源的代码，在自己的数据集上跑p-tuning，发现loss变为nan，查了之后模型输出的logit中的数据变为nan，这是什么原因啊，求助

**Comment by Xiao9905** [comment]
@effort-yq Hi，

这个问题感觉比较可能是你实现的数据集的故障，或者训练时lr之类的问题。请问有更详细的参考代码和你的实现细节么？
