### ISSUE TITLE
lstm的enbedding_dim与预训练模型的embedding_dim不一致的报错？

### ISSUE THREAD

**Issue by SCU-JJkinging** [THUDM/P-tuning#37]
![image](https://user-images.githubusercontent.com/59439162/170190966-c55d577a-57ae-4f0b-b28c-f33de4873fe3.png)
直接把项目git到本地跑，只把预训练模型换成了bert-base-cased，就报这个错，请问是什么原因呢？

![image](https://user-images.githubusercontent.com/59439162/170191325-7f20e2b2-4add-457d-9ea9-b0055c26fa94.png)
这两个维度不一致怎么复制呢？报错就是这一步操作

**Comment by Xiao9905** [comment]
Hi @SCU-JJkinging ,

是维度不一致的问题。原始实验是用的albert-xxlarge-v2，hidden size应该是1024；bert-base-cased是768。由于P-tuning的做法是把prompt位置的input embedding换成external trainable embedding，所以需要保持维度一致。

**Comment by SCU-JJkinging** [comment]
您好，请问如果用albert-xxlarge-v2的话，是需要把 prompt 的 embedding dim 也设置和albert一样吗？即1024

**Comment by Xiao9905** [comment]
@SCU-JJkinging ，

是的。我们的代码应当是默认使用的1024。

**Comment by SCU-JJkinging** [comment]
好的感谢！
![image](https://user-images.githubusercontent.com/59439162/170195774-13e37adc-e145-49f6-b298-bccc10913bb1.png)
但是您代码中默认使用的好像是128

**Comment by SCU-JJkinging** [comment]
还有个问题就是：我发现在分别使用用bert-base-cased 和albert-xxlarge-v2时，在RTE任务上的 acc 相差较大，能达到20%。所以我感觉预训练模型的选择很重要，是与预训练时使用的语料有关系吗？那这种效果的好坏岂不是主要取决于预训练模型的“好坏”呢？谢谢！

**Comment by Xiao9905** [comment]
@SCU-JJkinging ,

1. 这是因为albert-xxlarge-v2使用了Factorized embedding parameterization的技术，将一个1024的embedding分解为128的向量乘上一个128 * 1024的矩阵进行重参数化压缩参数量 
2. 这是显然的。决定任务性能的主要是与训练模型的质量，albert本来就是bert的一个升级版本；另外，不同预训练模型需要不同的超参数进行微调，直接使用我们在albert-xxlarge-v2上的最优超参，一般情况下无法在其他模型上得到最优结果
