### ISSUE TITLE
Fully-supervised SuperGLUE

### ISSUE THREAD

**Issue by zjujh1995** [THUDM/P-tuning#8]
Nice work. May I ask do you have a plan to release codes to re-implement P-tuning for fully-supervised SuperGLUE tasks? Seems there are no relevant codes yet.

**Comment by zheng-yanan** [comment]
> Nice work. May I ask do you have a plan to release codes to re-implement P-tuning for fully-supervised SuperGLUE tasks? Seems there are no relevant codes yet.

Hi! Thanks for your interest. We will release related templates as well as scripts for fully supervised settings. Since we are working on some additional experiments, it would take some time.

Thank you.

**Comment by Xiao9905** [comment]
Solved in previous update. Thanks for your comments.
